#!/usr/bin/env bash
# shellcheck disable=SC2129

set -ex

# 输出环境变量
echo "APP_NAME=${APP_NAME}"
echo "ASSETS_REPOSITORY=${ASSETS_REPOSITORY}"
echo "BINARY_NAME=${BINARY_NAME}"
echo "DISABLE_UPDATE=${DISABLE_UPDATE}"
echo "OS_NAME=${OS_NAME}"
echo "VERSIONS_REPOSITORY=${VERSIONS_REPOSITORY}"
echo "VSCODE_QUALITY=${VSCODE_QUALITY}"
echo "MS_TAG=${MS_TAG}"
echo "MS_COMMIT=${MS_COMMIT}"
echo "RELEASE_VERSION=${RELEASE_VERSION}"
echo "GENERATE_ASSETS=${GENERATE_ASSETS}"

export SHOULD_BUILD=yes
export SHOULD_DEPLOY=no
export VSCODE_QUALITY=stable

echo SHOULD_BUILD=${SHOULD_BUILD}
echo SHOULD_DEPLOY=${SHOULD_DEPLOY}
echo VSCODE_QUALITY=${VSCODE_QUALITY}
